# Bootstrap metagrammar
@header """\
using PySharp.SyntaxAnalysis.Tokens;
using PySharp.SyntaxAnalysis.Common;
using PySharp.SyntaxAnalysis.Common.Ast;
using PySharp.SyntaxAnalysis.Generator.Ast;

namespace PySharp.SyntaxAnalysis.Generator;
"""
@class_signature "internal class NewGrammarParser(ITokenNodeStream tokenStream) : BaseParser<GrammarNode>(tokenStream)"
@parse_call_return "GrammarNode"

@main
Start[GrammarNode]:
    | Meta+ Rule+ EndOfFile -> new GrammarNode(metaPlus, rulePlus)

Meta[MetadataNode]:
    | "@" Name StringLiteral NewLine -> new MetadataNode(name.RawString, StringParser.ParseQuotedString(stringliteral.RawString))

Rule[RuleNode]:
    | ("@" Name NewLine)* Name -TypeSpec ":" NewLine Indent ("|" Alternative NewLine)+ Dedent \
        -> new RuleNode([.. groupStar.Select(g => g.name.RawString)], name.RawString, typespec, 
                        [.. group1Plus.Select(g => g.alternative)]) 
    
    | ("@" Name NewLine)* Name -TypeSpec ":" Alternative NewLine \
        -> new RuleNode([.. groupStar.Select(g => g.name.RawString)], name.RawString, typespec, [alternative])

TypeSpec[TypeSpecNode]:
    | "[" Name "]" -> new TypeSpecNode(name.RawString)

Alternative[AlternativeNode]:
    | Molecule+ -Action -> new AlternativeNode(moleculePlus, action)

Molecule[MoleculeNode]:
    | "&" Atom -> new LookaheadNode(atom, true)
    | "!" Atom -> new LookaheadNode(atom, false)
    | "-" Atom -> new OptionalNode(atom)
    | Atom "*" -> new RepeatZeroMoreNode(atom)
    | Atom "+" -> new RepeatOneMoreNode(atom)
    | Atom -> new AtomMoleculeNode(atom)

Atom[AtomNode]:
    | "(" Alternative ")" -> new GroupAtomNode([alternative])
    | Name -> new NameAtomNode(name.RawString)
    | StringLiteral -> new StringAtomNode(stringliteral.RawString)

Action[ActionNode]:
    | "->" ActionStuff+ -> new ActionNode(actionstuffPlus.RecoverText())

@union
ActionStuff[TokenNode]:
    | Name
    | StringLiteral
    | "("
    | ")"
    | ","
    | "."
    | ">"
    | "<"
    | "="
    | "=="
    | ">="
    | "<="
    | "!"
    | "["
    | "]"
