# Bootstrap metagrammar
@header """\
using PySharp.SyntaxAnalysis.Tokens;
using PySharp.SyntaxAnalysis.Common;
using PySharp.SyntaxAnalysis.Common.Ast;
using PySharp.SyntaxAnalysis.Generator.Ast;

namespace PySharp.SyntaxAnalysis.Generator;
"""
@class_signature "internal class NewGrammarParser(ITokenNodeStream tokenStream) : BaseParser<GrammarNode>(tokenStream)"
@parse_call_return "GrammarNode"

@main
Start[GrammarNode]:
    | Meta+ Rule+ EndOfFile -> new GrammarNode(metaPlus, rulePlus)

Meta[MetadataNode]:
    | "@" Name StringLiteral NewLine -> new MetadataNode(name.RawString, StringParser.ParseQuotedString(stringliteral.RawString))

Rule[RuleNode]:
    | "@" Name NewLine Name -TypeSpec ":" NewLine Indent Alternative+ Dedent \
        -> new DecoratedRuleNode(name.RawString, name1.RawString, typespec, alternativePlus)
    | Name -TypeSpec ":" NewLine Indent Alternative+ Dedent -> new RuleNode(name.RawString, typespec, alternativePlus)

TypeSpec[TypeSpecNode]:
    | "[" Name "]" -> new TypeSpecNode(name.RawString)
    | "[" StringLiteral "]" -> new TypeSpecNode(StringParser.ParseQuotedString(stringliteral.RawString))

Alternative[AlternativeNode]:
    | "|" Molecule+ -Action NewLine -> new AlternativeNode(moleculePlus, action)

Molecule[MoleculeNode]:
    | "&" Atom -> new LookaheadNode(atom, true)
    | "!" Atom -> new LookaheadNode(atom, false)
    | "-" Atom -> new OptionalNode(atom)
    | Atom "*" -> new RepeatZeroMoreNode(atom)
    | Atom "+" -> new RepeatOneMoreNode(atom)
    | Atom -> new AtomMoleculeNode(atom)

Atom[AtomNode]:
    | Name -> new NameAtomNode(name.RawString)
    | StringLiteral -> new StringAtomNode(stringliteral.RawString)

Action[ActionNode]:
    | "->" ActionStuff+ -> new ActionNode(string.Join("", actionstuffPlus.Select(static a => a.RecoverText())))

@union
ActionStuff[TokenNode]:
    | Name
    | StringLiteral
    | "("
    | ")"
    | ","
    | "."
    | ">"
    | "<"
    | "="
    | "=="
    | ">="
    | "<="
    | "!"
