// <auto-generated/>
// Bau bau!

#nullable enable

// Generated from 'Meta.ebnf'
using PySharp.SyntaxAnalysis.Tokens;
using PySharp.SyntaxAnalysis.Common;
using PySharp.SyntaxAnalysis.Common.Ast;

namespace PySharp.SyntaxAnalysis.Generator;

internal class GrammarParser(ITokenNodeStream _tokenStream) : BaseParser<GrammarNode>(_tokenStream)
{
    protected override HashSet<string> Keywords => [];

    public override GrammarNode? Parse() => rule_Grammar();

    #region Grammar
    // @main
    // Grammar: Metadata* Rule* EndOfFile -> new(Metadata=metadata_Star, Rules=rule_Star)
    GrammarNode? rule_Grammar()
    {
        int _mark = base.Mark();
        {
            // Metadata* Rule* EndOfFile -> new(Metadata=metadata_Star, Rules=rule_Star)
            INodeArray<GreenNode>? metadata_Star;
            INodeArray<GreenNode>? rule_Star;
            GreenNode? end_of_file;
            if ((metadata_Star = base.Repeat(rule_Metadata, 0)) is not null
                &&
                (rule_Star = base.Repeat(rule_Rule, 0)) is not null
                &&
                (end_of_file = Expect(TokenType.EndOfFile)) is not null
            )
            {
                return new GrammarNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(metadata_Star),
                        new NodeList(rule_Star),
                        end_of_file,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Grammar

    #region Metadata
    // Metadata: "@" Name StringLiteral NewLine -> new(Key=name, Value=string_literal)
    MetadataNode? rule_Metadata()
    {
        int _mark = base.Mark();
        {
            // "@" Name StringLiteral NewLine -> new(Key=name, Value=string_literal)
            GreenNode? at;
            GreenNode? name;
            GreenNode? string_literal;
            GreenNode? new_line;
            if ((at = Expect(TokenType.At)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (string_literal = Expect(TokenType.StringLiteral)) is not null
                &&
                (new_line = Expect(TokenType.NewLine)) is not null
            )
            {
                return new MetadataNode()
                {
                    Children = new NodeArray<GreenNode>([
                        at,
                        name,
                        string_literal,
                        new_line,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Metadata

    #region Rule
    // Rule:
    //     | Decorator* Name ":" NewLine ~ Indent ("|" Alternative NewLine -> Arm(Alternative=alternative))+ Dedent \
    //         -> ArmedRule(Decorators=decorator_Star, Name=name, Arms=arm_Plus)
    //     | Decorator* Name ":" Alternative NewLine -> SingleAlternativeRule(Decorators=decorator_Star, Name=name, Alternative=alternative)
    RuleNode? rule_Rule()
    {
        int _mark = base.Mark();
        bool _cut = false;
        {
            // Decorator* Name ":" NewLine ~ Indent ("|" Alternative NewLine -> Arm(Alternative=alternative))+ Dedent \
            //         -> ArmedRule(Decorators=decorator_Star, Name=name, Arms=arm_Plus)
            INodeArray<GreenNode>? decorator_Star;
            GreenNode? name;
            GreenNode? colon;
            GreenNode? new_line;
            GreenNode? indent;
            INodeArray<GreenNode>? arm_Plus;
            GreenNode? dedent;
            if ((decorator_Star = base.Repeat(rule_Decorator, 0)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (colon = Expect(TokenType.Colon)) is not null
                &&
                (new_line = Expect(TokenType.NewLine)) is not null
                &&
                (_cut = true)
                &&
                (indent = Expect(TokenType.Indent)) is not null
                &&
                (arm_Plus = base.Repeat(rule_Arm, 1)) is not null
                &&
                (dedent = Expect(TokenType.Dedent)) is not null
            )
            {
                return new ArmedRuleNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(decorator_Star),
                        name,
                        colon,
                        new_line,
                        indent,
                        new NodeList(arm_Plus),
                        dedent,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // Decorator* Name ":" Alternative NewLine -> SingleAlternativeRule(Decorators=decorator_Star, Name=name, Alternative=alternative)
            INodeArray<GreenNode>? decorator_Star;
            GreenNode? name;
            GreenNode? colon;
            GreenNode? alternative;
            GreenNode? new_line;
            if ((decorator_Star = base.Repeat(rule_Decorator, 0)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (colon = Expect(TokenType.Colon)) is not null
                &&
                (alternative = rule_Alternative()) is not null
                &&
                (new_line = Expect(TokenType.NewLine)) is not null
            )
            {
                return new SingleAlternativeRuleNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(decorator_Star),
                        name,
                        colon,
                        alternative,
                        new_line,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Rule

    #region Arm
    // "|" Alternative NewLine -> Arm(Alternative=alternative)
    ArmNode? rule_Arm()
    {
        int _mark = base.Mark();
        {
            // "|" Alternative NewLine -> Arm(Alternative=alternative)
            GreenNode? vert_bar;
            GreenNode? alternative;
            GreenNode? new_line;
            if ((vert_bar = Expect(TokenType.VertBar)) is not null
                &&
                (alternative = rule_Alternative()) is not null
                &&
                (new_line = Expect(TokenType.NewLine)) is not null
            )
            {
                return new ArmNode()
                {
                    Children = new NodeArray<GreenNode>([
                        vert_bar,
                        alternative,
                        new_line,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Arm

    #region Decorator
    // Decorator: "@" Name NewLine -> new(Value=name)
    DecoratorNode? rule_Decorator()
    {
        int _mark = base.Mark();
        {
            // "@" Name NewLine -> new(Value=name)
            GreenNode? at;
            GreenNode? name;
            GreenNode? new_line;
            if ((at = Expect(TokenType.At)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (new_line = Expect(TokenType.NewLine)) is not null
            )
            {
                return new DecoratorNode()
                {
                    Children = new NodeArray<GreenNode>([
                        at,
                        name,
                        new_line,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Decorator

    #region Alternative
    // Alternative: Molecule+ -Action -> new(Molecules=molecule_Plus, Action=action)
    AlternativeNode? rule_Alternative()
    {
        int _mark = base.Mark();
        {
            // Molecule+ -Action -> new(Molecules=molecule_Plus, Action=action)
            INodeArray<GreenNode>? molecule_Plus;
            GreenNode? action;
            if ((molecule_Plus = base.Repeat(rule_Molecule, 1)) is not null
                &&
                ((action = rule_Action()) is not null || true) // Optional
            )
            {
                return new AlternativeNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(molecule_Plus),
                        action ?? VoidNode.Instance,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Alternative

    #region Molecule
    // Molecule:
    //     | "[" ~ Alternative+."|" "]" -> OptionalGroup(Alternatives=alternative_Gather)
    //     | "&" ~ Atom -> PositiveLookahead(Atom=atom)
    //     | "!" ~ Atom -> NegativeLookahead(Atom=atom)
    //     | "-" ~ Atom -> Optional(Atom=atom)
    //     | Atom "+" "." ~ Atom -> Gather(ValueAtom=atom, Separator=atom1)
    //     | Atom "+" -> RepeatOneMore(Atom=atom)
    //     | Atom "*" -> RepeatZeroMore(Atom=atom)
    //     | Atom -> AtomMolecule(Atom=atom)
    //     | "~" -> Cut()
    MoleculeNode? rule_Molecule()
    {
        int _mark = base.Mark();
        bool _cut = false;
        {
            // "[" ~ Alternative+."|" "]" -> OptionalGroup(Alternatives=alternative_Gather)
            GreenNode? left_square_bracket;
            INodeArray<GreenNode>? alternative_Gather;
            GreenNode? right_square_bracket;
            if ((left_square_bracket = Expect(TokenType.LeftSquareBracket)) is not null
                &&
                (_cut = true)
                &&
                (alternative_Gather = base.Gather(rule_Alternative, TokenType.VertBar)) is not null
                &&
                (right_square_bracket = Expect(TokenType.RightSquareBracket)) is not null
            )
            {
                return new OptionalGroupNode()
                {
                    Children = new NodeArray<GreenNode>([
                        left_square_bracket,
                        new NodeList(alternative_Gather),
                        right_square_bracket,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // "&" ~ Atom -> PositiveLookahead(Atom=atom)
            GreenNode? ampersand;
            GreenNode? atom;
            if ((ampersand = Expect(TokenType.Ampersand)) is not null
                &&
                (_cut = true)
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new PositiveLookaheadNode()
                {
                    Children = new NodeArray<GreenNode>([
                        ampersand,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // "!" ~ Atom -> NegativeLookahead(Atom=atom)
            GreenNode? exclamation;
            GreenNode? atom;
            if ((exclamation = Expect(TokenType.Exclamation)) is not null
                &&
                (_cut = true)
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new NegativeLookaheadNode()
                {
                    Children = new NodeArray<GreenNode>([
                        exclamation,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // "-" ~ Atom -> Optional(Atom=atom)
            GreenNode? minus;
            GreenNode? atom;
            if ((minus = Expect(TokenType.Minus)) is not null
                &&
                (_cut = true)
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new OptionalNode()
                {
                    Children = new NodeArray<GreenNode>([
                        minus,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // Atom "+" "." ~ Atom -> Gather(ValueAtom=atom, Separator=atom1)
            GreenNode? atom;
            GreenNode? plus;
            GreenNode? dot;
            GreenNode? atom1;
            if ((atom = rule_Atom()) is not null
                &&
                (plus = Expect(TokenType.Plus)) is not null
                &&
                (dot = Expect(TokenType.Dot)) is not null
                &&
                (_cut = true)
                &&
                (atom1 = rule_Atom()) is not null
            )
            {
                return new GatherNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        plus,
                        dot,
                        atom1,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // Atom "+" -> RepeatOneMore(Atom=atom)
            GreenNode? atom;
            GreenNode? plus;
            if ((atom = rule_Atom()) is not null
                &&
                (plus = Expect(TokenType.Plus)) is not null
            )
            {
                return new RepeatOneMoreNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        plus,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Atom "*" -> RepeatZeroMore(Atom=atom)
            GreenNode? atom;
            GreenNode? star;
            if ((atom = rule_Atom()) is not null
                &&
                (star = Expect(TokenType.Star)) is not null
            )
            {
                return new RepeatZeroMoreNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        star,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Atom -> AtomMolecule(Atom=atom)
            GreenNode? atom;
            if ((atom = rule_Atom()) is not null)
            {
                return new AtomMoleculeNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // "~" -> Cut()
            GreenNode? tilde;
            if ((tilde = Expect(TokenType.Tilde)) is not null)
            {
                return new CutNode()
                {
                    Children = new NodeArray<GreenNode>([
                        tilde,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Molecule

    #region Atom
    // Atom:
    //     | "(" ~ Alternative+."|" ")" -> GroupAtom(Alternatives=alternative_Gather)
    //     | Name -> NameAtom(Value=name)
    //     | StringLiteral -> StringAtom(Value=string_literal)
    AtomNode? rule_Atom()
    {
        int _mark = base.Mark();
        bool _cut = false;
        {
            // "(" ~ Alternative+."|" ")" -> GroupAtom(Alternatives=alternative_Gather)
            GreenNode? left_paren;
            INodeArray<GreenNode>? alternative_Gather;
            GreenNode? right_paren;
            if ((left_paren = Expect(TokenType.LeftParen)) is not null
                &&
                (_cut = true)
                &&
                (alternative_Gather = base.Gather(rule_Alternative, TokenType.VertBar)) is not null
                &&
                (right_paren = Expect(TokenType.RightParen)) is not null
            )
            {
                return new GroupAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        left_paren,
                        new NodeList(alternative_Gather),
                        right_paren,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // Name -> NameAtom(Value=name)
            GreenNode? name;
            if ((name = Expect(TokenType.Name)) is not null)
            {
                return new NameAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        name,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // StringLiteral -> StringAtom(Value=string_literal)
            GreenNode? string_literal;
            if ((string_literal = Expect(TokenType.StringLiteral)) is not null)
            {
                return new StringAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        string_literal,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Atom

    #region Action
    // Action:
    //     | "->" "new" ~ "(" [Target+."," -> Arguments(Value=target_Gather)] ")" -> InferredAction(Arguments=arguments)
    //     | "->" Name "(" [Target+."," -> Arguments(Value=target_Gather)] ")" -> NamedAction(Name=name, Arguments=arguments)
    ActionNode? rule_Action()
    {
        int _mark = base.Mark();
        bool _cut = false;
        {
            // "->" "new" ~ "(" [Target+."," -> Arguments(Value=target_Gather)] ")" -> InferredAction(Arguments=arguments)
            GreenNode? right_arrow;
            GreenNode? _string_token;
            GreenNode? left_paren;
            GreenNode? arguments;
            GreenNode? right_paren;
            if ((right_arrow = Expect(TokenType.RightArrow)) is not null
                &&
                (_string_token = Expect("new")) is not null
                &&
                (_cut = true)
                &&
                (left_paren = Expect(TokenType.LeftParen)) is not null
                &&
                ((arguments = rule_Arguments()) is not null || true) // Optional
                &&
                (right_paren = Expect(TokenType.RightParen)) is not null
            )
            {
                return new InferredActionNode()
                {
                    Children = new NodeArray<GreenNode>([
                        right_arrow,
                        _string_token,
                        left_paren,
                        arguments ?? VoidNode.Instance,
                        right_paren,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // "->" Name "(" [Target+."," -> Arguments(Value=target_Gather)] ")" -> NamedAction(Name=name, Arguments=arguments)
            GreenNode? right_arrow;
            GreenNode? name;
            GreenNode? left_paren;
            GreenNode? arguments;
            GreenNode? right_paren;
            if ((right_arrow = Expect(TokenType.RightArrow)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (left_paren = Expect(TokenType.LeftParen)) is not null
                &&
                ((arguments = rule_Arguments()) is not null || true) // Optional
                &&
                (right_paren = Expect(TokenType.RightParen)) is not null
            )
            {
                return new NamedActionNode()
                {
                    Children = new NodeArray<GreenNode>([
                        right_arrow,
                        name,
                        left_paren,
                        arguments ?? VoidNode.Instance,
                        right_paren,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Action

    #region Arguments
    // Target+."," -> Arguments(Value=target_Gather)
    ArgumentsNode? rule_Arguments()
    {
        int _mark = base.Mark();
        {
            // Target+."," -> Arguments(Value=target_Gather)
            INodeArray<GreenNode>? target_Gather;
            if ((target_Gather = base.Gather(rule_Target, TokenType.Comma)) is not null)
            {
                return new ArgumentsNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(target_Gather),
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Arguments

    #region Target
    // Target: Name "=" Name -> new(Field=name, Variable=name1)
    TargetNode? rule_Target()
    {
        int _mark = base.Mark();
        {
            // Name "=" Name -> new(Field=name, Variable=name1)
            GreenNode? name;
            GreenNode? equal;
            GreenNode? name1;
            if ((name = Expect(TokenType.Name)) is not null
                &&
                (equal = Expect(TokenType.Equal)) is not null
                &&
                (name1 = Expect(TokenType.Name)) is not null
            )
            {
                return new TargetNode()
                {
                    Children = new NodeArray<GreenNode>([
                        name,
                        equal,
                        name1,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Target
}
#region Type definitions
internal sealed partial record GrammarNode : GreenNode
{
    internal NodeArray<MetadataNode> Metadata => ((NodeList)Children![0]).GetArray<MetadataNode>();
    internal NodeArray<RuleNode> Rules => ((NodeList)Children![1]).GetArray<RuleNode>();
}

internal sealed partial record MetadataNode : GreenNode
{
    internal TokenNode Key => (TokenNode)Children![1];
    internal TokenNode Value => (TokenNode)Children![2];
}

internal abstract partial record RuleNode : GreenNode
{
    internal NodeArray<DecoratorNode> Decorators => ((NodeList)Children![0]).GetArray<DecoratorNode>();
    internal TokenNode Name => (TokenNode)Children![1];
}

internal sealed partial record ArmedRuleNode : RuleNode
{
    internal NodeArray<ArmNode> Arms => ((NodeList)Children![5]).GetArray<ArmNode>();
}

internal sealed partial record SingleAlternativeRuleNode : RuleNode
{
    internal AlternativeNode Alternative => (AlternativeNode)Children![3];
}

internal sealed partial record ArmNode : GreenNode
{
    internal AlternativeNode Alternative => (AlternativeNode)Children![1];
}

internal sealed partial record DecoratorNode : GreenNode
{
    internal TokenNode Value => (TokenNode)Children![1];
}

internal sealed partial record AlternativeNode : GreenNode
{
    internal NodeArray<MoleculeNode> Molecules => ((NodeList)Children![0]).GetArray<MoleculeNode>();
    internal ActionNode? Action => Children![1] as ActionNode;
}

internal abstract partial record MoleculeNode : GreenNode
{
}

internal sealed partial record OptionalGroupNode : MoleculeNode
{
    private global::System.Collections.Immutable.ImmutableArray<AlternativeNode>? _field_Alternatives = null;
    internal global::System.Collections.Immutable.ImmutableArray<AlternativeNode> Alternatives
    {
        get
        {
            if (_field_Alternatives is null)
            {
                var _tmp = AstAlternatives.Where(static (_, i) => i % 2 == 0).Cast<AlternativeNode>();
                _field_Alternatives = global::System.Collections.Immutable.ImmutableArray.ToImmutableArray(_tmp);
            }
            return _field_Alternatives.Value;
        }
    }
    internal NodeArray<GreenNode> AstAlternatives => (NodeArray<GreenNode>)((NodeList)Children![1]).Children!;
}

internal sealed partial record PositiveLookaheadNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![1];
}

internal sealed partial record NegativeLookaheadNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![1];
}

internal sealed partial record OptionalNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![1];
}

internal sealed partial record GatherNode : MoleculeNode
{
    internal AtomNode ValueAtom => (AtomNode)Children![0];
    internal AtomNode Separator => (AtomNode)Children![3];
}

internal sealed partial record RepeatOneMoreNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![0];
}

internal sealed partial record RepeatZeroMoreNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![0];
}

internal sealed partial record AtomMoleculeNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![0];
}

internal sealed partial record CutNode : MoleculeNode
{
}

internal abstract partial record AtomNode : GreenNode
{
}

internal sealed partial record GroupAtomNode : AtomNode
{
    private global::System.Collections.Immutable.ImmutableArray<AlternativeNode>? _field_Alternatives = null;
    internal global::System.Collections.Immutable.ImmutableArray<AlternativeNode> Alternatives
    {
        get
        {
            if (_field_Alternatives is null)
            {
                var _tmp = AstAlternatives.Where(static (_, i) => i % 2 == 0).Cast<AlternativeNode>();
                _field_Alternatives = global::System.Collections.Immutable.ImmutableArray.ToImmutableArray(_tmp);
            }
            return _field_Alternatives.Value;
        }
    }
    internal NodeArray<GreenNode> AstAlternatives => (NodeArray<GreenNode>)((NodeList)Children![1]).Children!;
}

internal sealed partial record NameAtomNode : AtomNode
{
    internal TokenNode Value => (TokenNode)Children![0];
}

internal sealed partial record StringAtomNode : AtomNode
{
    internal TokenNode Value => (TokenNode)Children![0];
}

internal abstract partial record ActionNode : GreenNode
{
    internal ArgumentsNode? Arguments => Children![3] as ArgumentsNode;
}

internal sealed partial record InferredActionNode : ActionNode
{
}

internal sealed partial record NamedActionNode : ActionNode
{
    internal TokenNode Name => (TokenNode)Children![1];
}

internal sealed partial record ArgumentsNode : GreenNode
{
    private global::System.Collections.Immutable.ImmutableArray<TargetNode>? _field_Value = null;
    internal global::System.Collections.Immutable.ImmutableArray<TargetNode> Value
    {
        get
        {
            if (_field_Value is null)
            {
                var _tmp = AstValue.Where(static (_, i) => i % 2 == 0).Cast<TargetNode>();
                _field_Value = global::System.Collections.Immutable.ImmutableArray.ToImmutableArray(_tmp);
            }
            return _field_Value.Value;
        }
    }
    internal NodeArray<GreenNode> AstValue => (NodeArray<GreenNode>)((NodeList)Children![0]).Children!;
}

internal sealed partial record TargetNode : GreenNode
{
    internal TokenNode Field => (TokenNode)Children![0];
    internal TokenNode Variable => (TokenNode)Children![2];
}
#endregion
