// <auto-generated/>
// Bau bau!

#nullable enable

// Generated from 'Meta.ebnf'
using PySharp.SyntaxAnalysis.Tokens;
using PySharp.SyntaxAnalysis.Common;
using PySharp.SyntaxAnalysis.Common.Ast;

namespace PySharp.SyntaxAnalysis.Generator;

internal class GrammarParser(ITokenNodeStream _tokenStream) : BaseParser<GrammarNode>(_tokenStream)
{
    protected override HashSet<string> Keywords => [];

    public override GrammarNode? Parse() => rule_Grammar();

    #region Grammar
    // @main
    // Grammar: Metadata* Rule* EndOfFile -> new(Metadata=metadataStar, Rules=ruleStar)
    GrammarNode? rule_Grammar()
    {
        int _mark = base.Mark();
        {
            // Metadata* Rule* EndOfFile -> new(Metadata=metadataStar, Rules=ruleStar)
            INodeArray<GreenNode>? metadataStar;
            INodeArray<GreenNode>? ruleStar;
            GreenNode? endoffile;
            if ((metadataStar = base.Repeat(rule_Metadata, 0)) is not null
                &&
                (ruleStar = base.Repeat(rule_Rule, 0)) is not null
                &&
                (endoffile = Expect(TokenType.EndOfFile)) is not null
            )
            {
                return new GrammarNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(metadataStar),
                        new NodeList(ruleStar),
                        endoffile,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Grammar

    #region Metadata
    // Metadata: "@" Name StringLiteral NewLine -> new(Key=name, Value=stringliteral)
    MetadataNode? rule_Metadata()
    {
        int _mark = base.Mark();
        {
            // "@" Name StringLiteral NewLine -> new(Key=name, Value=stringliteral)
            GreenNode? at;
            GreenNode? name;
            GreenNode? stringliteral;
            GreenNode? newline;
            if ((at = Expect(TokenType.At)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (stringliteral = Expect(TokenType.StringLiteral)) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
            )
            {
                return new MetadataNode()
                {
                    Children = new NodeArray<GreenNode>([
                        at,
                        name,
                        stringliteral,
                        newline,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Metadata

    #region Rule
    // Rule:
    //     | Decorator* Name ":" NewLine ~ Indent ("|" Alternative NewLine -> Arm(Alternative=alternative))+ Dedent \
    //         -> ArmedRule(Decorators=decoratorStar, Name=name, Arms=armPlus)
    //     | Decorator* Name ":" Alternative NewLine -> SingleAlternativeRule(Decorators=decoratorStar, Name=name, Alternative=alternative)
    RuleNode? rule_Rule()
    {
        int _mark = base.Mark();
        bool _cut = false;
        {
            // Decorator* Name ":" NewLine ~ Indent ("|" Alternative NewLine -> Arm(Alternative=alternative))+ Dedent \
            //         -> ArmedRule(Decorators=decoratorStar, Name=name, Arms=armPlus)
            INodeArray<GreenNode>? decoratorStar;
            GreenNode? name;
            GreenNode? colon;
            GreenNode? newline;
            GreenNode? indent;
            INodeArray<GreenNode>? armPlus;
            GreenNode? dedent;
            if ((decoratorStar = base.Repeat(rule_Decorator, 0)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (colon = Expect(TokenType.Colon)) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
                &&
                (_cut = true)
                &&
                (indent = Expect(TokenType.Indent)) is not null
                &&
                (armPlus = base.Repeat(rule_Arm, 1)) is not null
                &&
                (dedent = Expect(TokenType.Dedent)) is not null
            )
            {
                return new ArmedRuleNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(decoratorStar),
                        name,
                        colon,
                        newline,
                        indent,
                        new NodeList(armPlus),
                        dedent,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // Decorator* Name ":" Alternative NewLine -> SingleAlternativeRule(Decorators=decoratorStar, Name=name, Alternative=alternative)
            INodeArray<GreenNode>? decoratorStar;
            GreenNode? name;
            GreenNode? colon;
            GreenNode? alternative;
            GreenNode? newline;
            if ((decoratorStar = base.Repeat(rule_Decorator, 0)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (colon = Expect(TokenType.Colon)) is not null
                &&
                (alternative = rule_Alternative()) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
            )
            {
                return new SingleAlternativeRuleNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(decoratorStar),
                        name,
                        colon,
                        alternative,
                        newline,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Rule

    #region Arm
    // "|" Alternative NewLine -> Arm(Alternative=alternative)
    ArmNode? rule_Arm()
    {
        int _mark = base.Mark();
        {
            // "|" Alternative NewLine -> Arm(Alternative=alternative)
            GreenNode? vertbar;
            GreenNode? alternative;
            GreenNode? newline;
            if ((vertbar = Expect(TokenType.VertBar)) is not null
                &&
                (alternative = rule_Alternative()) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
            )
            {
                return new ArmNode()
                {
                    Children = new NodeArray<GreenNode>([
                        vertbar,
                        alternative,
                        newline,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Arm

    #region Decorator
    // Decorator: "@" Name NewLine -> new(Value=name)
    DecoratorNode? rule_Decorator()
    {
        int _mark = base.Mark();
        {
            // "@" Name NewLine -> new(Value=name)
            GreenNode? at;
            GreenNode? name;
            GreenNode? newline;
            if ((at = Expect(TokenType.At)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
            )
            {
                return new DecoratorNode()
                {
                    Children = new NodeArray<GreenNode>([
                        at,
                        name,
                        newline,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Decorator

    #region Alternative
    // Alternative: Molecule+ -Action -> new(Molecules=moleculePlus, Action=action)
    AlternativeNode? rule_Alternative()
    {
        int _mark = base.Mark();
        {
            // Molecule+ -Action -> new(Molecules=moleculePlus, Action=action)
            INodeArray<GreenNode>? moleculePlus;
            GreenNode? action;
            if ((moleculePlus = base.Repeat(rule_Molecule, 1)) is not null
                &&
                ((action = rule_Action()) is not null || true) // Optional
            )
            {
                return new AlternativeNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(moleculePlus),
                        action ?? VoidNode.Instance,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Alternative

    #region Molecule
    // Molecule:
    //     | "[" ~ Alternative+."|" "]" -> OptionalGroup(Alternatives=alternativeGather)
    //     | "&" ~ Atom -> PositiveLookahead(Atom=atom)
    //     | "!" ~ Atom -> NegativeLookahead(Atom=atom)
    //     | "-" ~ Atom -> Optional(Atom=atom)
    //     | Atom "+" "." ~ Atom -> Gather(ValueAtom=atom, Separator=atom1)
    //     | Atom "+" -> RepeatOneMore(Atom=atom)
    //     | Atom "*" -> RepeatZeroMore(Atom=atom)
    //     | Atom -> AtomMolecule(Atom=atom)
    //     | "~" -> Cut()
    MoleculeNode? rule_Molecule()
    {
        int _mark = base.Mark();
        bool _cut = false;
        {
            // "[" ~ Alternative+."|" "]" -> OptionalGroup(Alternatives=alternativeGather)
            GreenNode? leftsquarebracket;
            INodeArray<GreenNode>? alternativeGather;
            GreenNode? rightsquarebracket;
            if ((leftsquarebracket = Expect(TokenType.LeftSquareBracket)) is not null
                &&
                (_cut = true)
                &&
                (alternativeGather = base.Gather(rule_Alternative, TokenType.VertBar)) is not null
                &&
                (rightsquarebracket = Expect(TokenType.RightSquareBracket)) is not null
            )
            {
                return new OptionalGroupNode()
                {
                    Children = new NodeArray<GreenNode>([
                        leftsquarebracket,
                        new NodeList(alternativeGather),
                        rightsquarebracket,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // "&" ~ Atom -> PositiveLookahead(Atom=atom)
            GreenNode? ampersand;
            GreenNode? atom;
            if ((ampersand = Expect(TokenType.Ampersand)) is not null
                &&
                (_cut = true)
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new PositiveLookaheadNode()
                {
                    Children = new NodeArray<GreenNode>([
                        ampersand,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // "!" ~ Atom -> NegativeLookahead(Atom=atom)
            GreenNode? exclamation;
            GreenNode? atom;
            if ((exclamation = Expect(TokenType.Exclamation)) is not null
                &&
                (_cut = true)
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new NegativeLookaheadNode()
                {
                    Children = new NodeArray<GreenNode>([
                        exclamation,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // "-" ~ Atom -> Optional(Atom=atom)
            GreenNode? minus;
            GreenNode? atom;
            if ((minus = Expect(TokenType.Minus)) is not null
                &&
                (_cut = true)
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new OptionalNode()
                {
                    Children = new NodeArray<GreenNode>([
                        minus,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // Atom "+" "." ~ Atom -> Gather(ValueAtom=atom, Separator=atom1)
            GreenNode? atom;
            GreenNode? plus;
            GreenNode? dot;
            GreenNode? atom1;
            if ((atom = rule_Atom()) is not null
                &&
                (plus = Expect(TokenType.Plus)) is not null
                &&
                (dot = Expect(TokenType.Dot)) is not null
                &&
                (_cut = true)
                &&
                (atom1 = rule_Atom()) is not null
            )
            {
                return new GatherNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        plus,
                        dot,
                        atom1,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // Atom "+" -> RepeatOneMore(Atom=atom)
            GreenNode? atom;
            GreenNode? plus;
            if ((atom = rule_Atom()) is not null
                &&
                (plus = Expect(TokenType.Plus)) is not null
            )
            {
                return new RepeatOneMoreNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        plus,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Atom "*" -> RepeatZeroMore(Atom=atom)
            GreenNode? atom;
            GreenNode? star;
            if ((atom = rule_Atom()) is not null
                &&
                (star = Expect(TokenType.Star)) is not null
            )
            {
                return new RepeatZeroMoreNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        star,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Atom -> AtomMolecule(Atom=atom)
            GreenNode? atom;
            if ((atom = rule_Atom()) is not null)
            {
                return new AtomMoleculeNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // "~" -> Cut()
            GreenNode? tilde;
            if ((tilde = Expect(TokenType.Tilde)) is not null)
            {
                return new CutNode()
                {
                    Children = new NodeArray<GreenNode>([
                        tilde,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Molecule

    #region Atom
    // Atom:
    //     | "(" ~ Alternative+."|" ")" -> GroupAtom(Alternatives=alternativeGather)
    //     | Name -> NameAtom(Value=name)
    //     | StringLiteral -> StringAtom(Value=stringliteral)
    AtomNode? rule_Atom()
    {
        int _mark = base.Mark();
        bool _cut = false;
        {
            // "(" ~ Alternative+."|" ")" -> GroupAtom(Alternatives=alternativeGather)
            GreenNode? leftparen;
            INodeArray<GreenNode>? alternativeGather;
            GreenNode? rightparen;
            if ((leftparen = Expect(TokenType.LeftParen)) is not null
                &&
                (_cut = true)
                &&
                (alternativeGather = base.Gather(rule_Alternative, TokenType.VertBar)) is not null
                &&
                (rightparen = Expect(TokenType.RightParen)) is not null
            )
            {
                return new GroupAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        leftparen,
                        new NodeList(alternativeGather),
                        rightparen,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // Name -> NameAtom(Value=name)
            GreenNode? name;
            if ((name = Expect(TokenType.Name)) is not null)
            {
                return new NameAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        name,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // StringLiteral -> StringAtom(Value=stringliteral)
            GreenNode? stringliteral;
            if ((stringliteral = Expect(TokenType.StringLiteral)) is not null)
            {
                return new StringAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        stringliteral,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Atom

    #region Action
    // Action:
    //     | "->" "new" ~ "(" [Target+."," -> Arguments(Value=targetGather)] ")" -> InferredAction(Arguments=arguments)
    //     | "->" Name "(" [Target+."," -> Arguments(Value=targetGather)] ")" -> NamedAction(Name=name, Arguments=arguments)
    ActionNode? rule_Action()
    {
        int _mark = base.Mark();
        bool _cut = false;
        {
            // "->" "new" ~ "(" [Target+."," -> Arguments(Value=targetGather)] ")" -> InferredAction(Arguments=arguments)
            GreenNode? rightarrow;
            GreenNode? __token1;
            GreenNode? leftparen;
            GreenNode? arguments;
            GreenNode? rightparen;
            if ((rightarrow = Expect(TokenType.RightArrow)) is not null
                &&
                (__token1 = Expect("new")) is not null
                &&
                (_cut = true)
                &&
                (leftparen = Expect(TokenType.LeftParen)) is not null
                &&
                ((arguments = rule_Arguments()) is not null || true) // Optional
                &&
                (rightparen = Expect(TokenType.RightParen)) is not null
            )
            {
                return new InferredActionNode()
                {
                    Children = new NodeArray<GreenNode>([
                        rightarrow,
                        __token1,
                        leftparen,
                        arguments ?? VoidNode.Instance,
                        rightparen,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        if (_cut)
        {
            return null;
        }
        {
            // "->" Name "(" [Target+."," -> Arguments(Value=targetGather)] ")" -> NamedAction(Name=name, Arguments=arguments)
            GreenNode? rightarrow;
            GreenNode? name;
            GreenNode? leftparen;
            GreenNode? arguments;
            GreenNode? rightparen;
            if ((rightarrow = Expect(TokenType.RightArrow)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (leftparen = Expect(TokenType.LeftParen)) is not null
                &&
                ((arguments = rule_Arguments()) is not null || true) // Optional
                &&
                (rightparen = Expect(TokenType.RightParen)) is not null
            )
            {
                return new NamedActionNode()
                {
                    Children = new NodeArray<GreenNode>([
                        rightarrow,
                        name,
                        leftparen,
                        arguments ?? VoidNode.Instance,
                        rightparen,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Action

    #region Arguments
    // Target+."," -> Arguments(Value=targetGather)
    ArgumentsNode? rule_Arguments()
    {
        int _mark = base.Mark();
        {
            // Target+."," -> Arguments(Value=targetGather)
            INodeArray<GreenNode>? targetGather;
            if ((targetGather = base.Gather(rule_Target, TokenType.Comma)) is not null)
            {
                return new ArgumentsNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(targetGather),
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Arguments

    #region Target
    // Target: Name "=" Name -> new(Field=name, Variable=name1)
    TargetNode? rule_Target()
    {
        int _mark = base.Mark();
        {
            // Name "=" Name -> new(Field=name, Variable=name1)
            GreenNode? name;
            GreenNode? equal;
            GreenNode? name1;
            if ((name = Expect(TokenType.Name)) is not null
                &&
                (equal = Expect(TokenType.Equal)) is not null
                &&
                (name1 = Expect(TokenType.Name)) is not null
            )
            {
                return new TargetNode()
                {
                    Children = new NodeArray<GreenNode>([
                        name,
                        equal,
                        name1,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Target
}

internal partial record GrammarNode : GreenNode
{
    internal NodeArray<MetadataNode> Metadata => ((NodeList)Children![0]).GetArray<MetadataNode>();
    internal NodeArray<RuleNode> Rules => ((NodeList)Children![1]).GetArray<RuleNode>();
}

internal partial record MetadataNode : GreenNode
{
    internal TokenNode Key => (TokenNode)Children![1];
    internal TokenNode Value => (TokenNode)Children![2];
}

internal partial record RuleNode : GreenNode
{
    internal NodeArray<DecoratorNode> Decorators => ((NodeList)Children![0]).GetArray<DecoratorNode>();
    internal TokenNode Name => (TokenNode)Children![1];
}

internal partial record ArmedRuleNode : RuleNode
{
    internal NodeArray<ArmNode> Arms => ((NodeList)Children![5]).GetArray<ArmNode>();
}

internal partial record SingleAlternativeRuleNode : RuleNode
{
    internal AlternativeNode Alternative => (AlternativeNode)Children![3];
}

internal partial record ArmNode : GreenNode
{
    internal AlternativeNode Alternative => (AlternativeNode)Children![1];
}

internal partial record DecoratorNode : GreenNode
{
    internal TokenNode Value => (TokenNode)Children![1];
}

internal partial record AlternativeNode : GreenNode
{
    internal NodeArray<MoleculeNode> Molecules => ((NodeList)Children![0]).GetArray<MoleculeNode>();
    internal ActionNode? Action => Children![1] as ActionNode;
}

internal partial record MoleculeNode : GreenNode
{
}

internal partial record OptionalGroupNode : MoleculeNode
{
    private global::System.Collections.Immutable.ImmutableArray<AlternativeNode>? _field_Alternatives = null;
    internal global::System.Collections.Immutable.ImmutableArray<AlternativeNode> Alternatives
    {
        get
        {
            if (_field_Alternatives is null)
            {
                var _tmp = AstAlternatives.Where(static (_, i) => i % 2 == 0).Cast<AlternativeNode>();
                _field_Alternatives = global::System.Collections.Immutable.ImmutableArray.ToImmutableArray(_tmp);
            }
            return _field_Alternatives.Value;
        }
    }
    internal NodeArray<GreenNode> AstAlternatives => (NodeArray<GreenNode>)((NodeList)Children![1]).Children!;
}

internal partial record PositiveLookaheadNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![1];
}

internal partial record NegativeLookaheadNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![1];
}

internal partial record OptionalNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![1];
}

internal partial record GatherNode : MoleculeNode
{
    internal AtomNode ValueAtom => (AtomNode)Children![0];
    internal AtomNode Separator => (AtomNode)Children![3];
}

internal partial record RepeatOneMoreNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![0];
}

internal partial record RepeatZeroMoreNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![0];
}

internal partial record AtomMoleculeNode : MoleculeNode
{
    internal AtomNode Atom => (AtomNode)Children![0];
}

internal partial record CutNode : MoleculeNode
{
}

internal partial record AtomNode : GreenNode
{
}

internal partial record GroupAtomNode : AtomNode
{
    private global::System.Collections.Immutable.ImmutableArray<AlternativeNode>? _field_Alternatives = null;
    internal global::System.Collections.Immutable.ImmutableArray<AlternativeNode> Alternatives
    {
        get
        {
            if (_field_Alternatives is null)
            {
                var _tmp = AstAlternatives.Where(static (_, i) => i % 2 == 0).Cast<AlternativeNode>();
                _field_Alternatives = global::System.Collections.Immutable.ImmutableArray.ToImmutableArray(_tmp);
            }
            return _field_Alternatives.Value;
        }
    }
    internal NodeArray<GreenNode> AstAlternatives => (NodeArray<GreenNode>)((NodeList)Children![1]).Children!;
}

internal partial record NameAtomNode : AtomNode
{
    internal TokenNode Value => (TokenNode)Children![0];
}

internal partial record StringAtomNode : AtomNode
{
    internal TokenNode Value => (TokenNode)Children![0];
}

internal partial record ActionNode : GreenNode
{
    internal ArgumentsNode? Arguments => Children![3] as ArgumentsNode;
}

internal partial record InferredActionNode : ActionNode
{
}

internal partial record NamedActionNode : ActionNode
{
    internal TokenNode Name => (TokenNode)Children![1];
}

internal partial record ArgumentsNode : GreenNode
{
    private global::System.Collections.Immutable.ImmutableArray<TargetNode>? _field_Value = null;
    internal global::System.Collections.Immutable.ImmutableArray<TargetNode> Value
    {
        get
        {
            if (_field_Value is null)
            {
                var _tmp = AstValue.Where(static (_, i) => i % 2 == 0).Cast<TargetNode>();
                _field_Value = global::System.Collections.Immutable.ImmutableArray.ToImmutableArray(_tmp);
            }
            return _field_Value.Value;
        }
    }
    internal NodeArray<GreenNode> AstValue => (NodeArray<GreenNode>)((NodeList)Children![0]).Children!;
}

internal partial record TargetNode : GreenNode
{
    internal TokenNode Field => (TokenNode)Children![0];
    internal TokenNode Variable => (TokenNode)Children![2];
}
