// <auto-generated/>
// Bau bau!
#nullable enable

// Generated from 'Meta.ebnf'
using PySharp.SyntaxAnalysis.Tokens;
using PySharp.SyntaxAnalysis.Common;
using PySharp.SyntaxAnalysis.Common.Ast;
using PySharp.SyntaxAnalysis.Generator.Ast;
namespace PySharp.SyntaxAnalysis.Generator;

internal class GrammarParser(ITokenNodeStream _tokenStream) : BaseParser<GrammarNode>(_tokenStream)
{
    protected override HashSet<string> Keywords => [];
    public override GrammarNode? Parse() => rule_Grammar();
    #region Grammar
    // @main
    // Grammar: Metadata* Rule* EndOfFile -> new(Metadata=metadataStar Rules=ruleStar)
    GrammarNode? rule_Grammar()
    {
        int _mark = base.Mark();
        {
            // Metadata* Rule* EndOfFile -> new(Metadata=metadataStar Rules=ruleStar)
            INodeArray<GreenNode>? metadataStar;
            INodeArray<GreenNode>? ruleStar;
            GreenNode? endoffile;
            if ((metadataStar = base.Repeat(rule_Metadata, 0)) is not null
                &&
                (ruleStar = base.Repeat(rule_Rule, 0)) is not null
                &&
                (endoffile = Expect(TokenType.EndOfFile)) is not null
            )
            {
                return new GrammarNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(metadataStar),
                        new NodeList(ruleStar),
                        endoffile,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Grammar
    #region Metadata
    // Metadata: "@" Name StringLiteral NewLine -> new(Key=name Value=stringliteral)
    MetadataNode? rule_Metadata()
    {
        int _mark = base.Mark();
        {
            // "@" Name StringLiteral NewLine -> new(Key=name Value=stringliteral)
            GreenNode? at;
            GreenNode? name;
            GreenNode? stringliteral;
            GreenNode? newline;
            if ((at = Expect(TokenType.At)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (stringliteral = Expect(TokenType.StringLiteral)) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
            )
            {
                return new MetadataNode()
                {
                    Children = new NodeArray<GreenNode>([
                        at,
                        name,
                        stringliteral,
                        newline,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Metadata
    #region Rule
    // Rule:
    //     | Decorator* Name ":" NewLine Indent ("|" Alternative NewLine -> Arm(Alternative=alternative))+ Dedent \
    //         -> ArmedRule(Decorators=decoratorStar Name=name Arms=groupPlus)
    //     | Decorator* Name ":" Alternative NewLine -> SingleAlternativeRule(Decorators=decoratorStar Name=name Alternative=alternative)
    RuleNode? rule_Rule()
    {
        int _mark = base.Mark();
        {
            // Decorator* Name ":" NewLine Indent ("|" Alternative NewLine -> Arm(Alternative=alternative))+ Dedent \
            //         -> ArmedRule(Decorators=decoratorStar Name=name Arms=groupPlus)
            INodeArray<GreenNode>? decoratorStar;
            GreenNode? name;
            GreenNode? colon;
            GreenNode? newline;
            GreenNode? indent;
            INodeArray<GreenNode>? groupPlus;
            GreenNode? dedent;
            if ((decoratorStar = base.Repeat(rule_Decorator, 0)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (colon = Expect(TokenType.Colon)) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
                &&
                (indent = Expect(TokenType.Indent)) is not null
                &&
                (groupPlus = base.Repeat(rule_Arm, 1)) is not null
                &&
                (dedent = Expect(TokenType.Dedent)) is not null
            )
            {
                return new ArmedRuleNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(decoratorStar),
                        name,
                        colon,
                        newline,
                        indent,
                        new NodeList(groupPlus),
                        dedent,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Decorator* Name ":" Alternative NewLine -> SingleAlternativeRule(Decorators=decoratorStar Name=name Alternative=alternative)
            INodeArray<GreenNode>? decoratorStar;
            GreenNode? name;
            GreenNode? colon;
            GreenNode? alternative;
            GreenNode? newline;
            if ((decoratorStar = base.Repeat(rule_Decorator, 0)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (colon = Expect(TokenType.Colon)) is not null
                &&
                (alternative = rule_Alternative()) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
            )
            {
                return new SingleAlternativeRuleNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(decoratorStar),
                        name,
                        colon,
                        alternative,
                        newline,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Rule
    #region Arm
    // "|" Alternative NewLine -> Arm(Alternative=alternative)
    ArmNode? rule_Arm()
    {
        int _mark = base.Mark();
        {
            // "|" Alternative NewLine -> Arm(Alternative=alternative)
            GreenNode? vertbar;
            GreenNode? alternative;
            GreenNode? newline;
            if ((vertbar = Expect(TokenType.VertBar)) is not null
                &&
                (alternative = rule_Alternative()) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
            )
            {
                return new ArmNode()
                {
                    Children = new NodeArray<GreenNode>([
                        vertbar,
                        alternative,
                        newline,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Arm
    #region Decorator
    // Decorator: "@" Name NewLine -> new(Value=name)
    DecoratorNode? rule_Decorator()
    {
        int _mark = base.Mark();
        {
            // "@" Name NewLine -> new(Value=name)
            GreenNode? at;
            GreenNode? name;
            GreenNode? newline;
            if ((at = Expect(TokenType.At)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (newline = Expect(TokenType.NewLine)) is not null
            )
            {
                return new DecoratorNode()
                {
                    Children = new NodeArray<GreenNode>([
                        at,
                        name,
                        newline,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Decorator
    #region Alternative
    // Alternative: Molecule+ -Action -> new(Molecules=moleculePlus Action=action)
    AlternativeNode? rule_Alternative()
    {
        int _mark = base.Mark();
        {
            // Molecule+ -Action -> new(Molecules=moleculePlus Action=action)
            INodeArray<GreenNode>? moleculePlus;
            GreenNode? action;
            if ((moleculePlus = base.Repeat(rule_Molecule, 1)) is not null
                &&
                ((action = rule_Action()) is not null || true) // Optional
            )
            {
                return new AlternativeNode()
                {
                    Children = new NodeArray<GreenNode>([
                        new NodeList(moleculePlus),
                        action ?? VoidNode.Instance,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Alternative
    #region Molecule
    // Molecule:
    //     | "&" Atom -> PositiveLookahead(Atom=atom)
    //     | "!" Atom -> NegativeLookahead(Atom=atom)
    //     | "-" Atom -> Optional(Atom=atom)
    //     | Atom "+" "." Atom -> Gather(ValueAtom=atom Separator=atom1)
    //     | Atom "+" -> RepeatOneMore(Atom=atom)
    //     | Atom "*" -> RepeatZeroMore(Atom=atom)
    //     | Atom -> AtomMolecule(Atom=atom)
    MoleculeNode? rule_Molecule()
    {
        int _mark = base.Mark();
        {
            // "&" Atom -> PositiveLookahead(Atom=atom)
            GreenNode? ampersand;
            GreenNode? atom;
            if ((ampersand = Expect(TokenType.Ampersand)) is not null
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new PositiveLookaheadNode()
                {
                    Children = new NodeArray<GreenNode>([
                        ampersand,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // "!" Atom -> NegativeLookahead(Atom=atom)
            GreenNode? exclamation;
            GreenNode? atom;
            if ((exclamation = Expect(TokenType.Exclamation)) is not null
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new NegativeLookaheadNode()
                {
                    Children = new NodeArray<GreenNode>([
                        exclamation,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // "-" Atom -> Optional(Atom=atom)
            GreenNode? minus;
            GreenNode? atom;
            if ((minus = Expect(TokenType.Minus)) is not null
                &&
                (atom = rule_Atom()) is not null
            )
            {
                return new OptionalNode()
                {
                    Children = new NodeArray<GreenNode>([
                        minus,
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Atom "+" "." Atom -> Gather(ValueAtom=atom Separator=atom1)
            GreenNode? atom;
            GreenNode? plus;
            GreenNode? dot;
            GreenNode? atom1;
            if ((atom = rule_Atom()) is not null
                &&
                (plus = Expect(TokenType.Plus)) is not null
                &&
                (dot = Expect(TokenType.Dot)) is not null
                &&
                (atom1 = rule_Atom()) is not null
            )
            {
                return new GatherNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        plus,
                        dot,
                        atom1,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Atom "+" -> RepeatOneMore(Atom=atom)
            GreenNode? atom;
            GreenNode? plus;
            if ((atom = rule_Atom()) is not null
                &&
                (plus = Expect(TokenType.Plus)) is not null
            )
            {
                return new RepeatOneMoreNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        plus,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Atom "*" -> RepeatZeroMore(Atom=atom)
            GreenNode? atom;
            GreenNode? star;
            if ((atom = rule_Atom()) is not null
                &&
                (star = Expect(TokenType.Star)) is not null
            )
            {
                return new RepeatZeroMoreNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                        star,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Atom -> AtomMolecule(Atom=atom)
            GreenNode? atom;
            if ((atom = rule_Atom()) is not null)
            {
                return new AtomMoleculeNode()
                {
                    Children = new NodeArray<GreenNode>([
                        atom,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Molecule
    #region Atom
    // Atom:
    //     | "(" Alternative ")" -> GroupAtom(Alternative=alternative)
    //     | Name -> NameAtom(Value=name)
    //     | StringLiteral -> StringAtom(Value=stringliteral)
    AtomNode? rule_Atom()
    {
        int _mark = base.Mark();
        {
            // "(" Alternative ")" -> GroupAtom(Alternative=alternative)
            GreenNode? leftparen;
            GreenNode? alternative;
            GreenNode? rightparen;
            if ((leftparen = Expect(TokenType.LeftParen)) is not null
                &&
                (alternative = rule_Alternative()) is not null
                &&
                (rightparen = Expect(TokenType.RightParen)) is not null
            )
            {
                return new GroupAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        leftparen,
                        alternative,
                        rightparen,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // Name -> NameAtom(Value=name)
            GreenNode? name;
            if ((name = Expect(TokenType.Name)) is not null)
            {
                return new NameAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        name,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // StringLiteral -> StringAtom(Value=stringliteral)
            GreenNode? stringliteral;
            if ((stringliteral = Expect(TokenType.StringLiteral)) is not null)
            {
                return new StringAtomNode()
                {
                    Children = new NodeArray<GreenNode>([
                        stringliteral,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Atom
    #region Action
    // Action:
    //     | "->" "new" "(" Target+."," ")" -> InferredAction(Arguments=targetGather)
    //     | "->" Name "(" Target+."," ")" -> NamedAction(Name=name Arguments=targetGather)
    ActionNode? rule_Action()
    {
        int _mark = base.Mark();
        {
            // "->" "new" "(" Target+."," ")" -> InferredAction(Arguments=targetGather)
            GreenNode? rightarrow;
            GreenNode? __token1;
            GreenNode? leftparen;
            INodeArray<GreenNode>? targetGather;
            GreenNode? rightparen;
            if ((rightarrow = Expect(TokenType.RightArrow)) is not null
                &&
                (__token1 = Expect("new")) is not null
                &&
                (leftparen = Expect(TokenType.LeftParen)) is not null
                &&
                (targetGather = base.Gather(rule_Target, TokenType.Comma)) is not null
                &&
                (rightparen = Expect(TokenType.RightParen)) is not null
            )
            {
                return new InferredActionNode()
                {
                    Children = new NodeArray<GreenNode>([
                        rightarrow,
                        __token1,
                        leftparen,
                        new NodeList(targetGather),
                        rightparen,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        {
            // "->" Name "(" Target+."," ")" -> NamedAction(Name=name Arguments=targetGather)
            GreenNode? rightarrow;
            GreenNode? name;
            GreenNode? leftparen;
            INodeArray<GreenNode>? targetGather;
            GreenNode? rightparen;
            if ((rightarrow = Expect(TokenType.RightArrow)) is not null
                &&
                (name = Expect(TokenType.Name)) is not null
                &&
                (leftparen = Expect(TokenType.LeftParen)) is not null
                &&
                (targetGather = base.Gather(rule_Target, TokenType.Comma)) is not null
                &&
                (rightparen = Expect(TokenType.RightParen)) is not null
            )
            {
                return new NamedActionNode()
                {
                    Children = new NodeArray<GreenNode>([
                        rightarrow,
                        name,
                        leftparen,
                        new NodeList(targetGather),
                        rightparen,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Action
    #region Target
    // Target: Name "=" Name -> new(Field=name Variable=name1)
    TargetNode? rule_Target()
    {
        int _mark = base.Mark();
        {
            // Name "=" Name -> new(Field=name Variable=name1)
            GreenNode? name;
            GreenNode? equal;
            GreenNode? name1;
            if ((name = Expect(TokenType.Name)) is not null
                &&
                (equal = Expect(TokenType.Equal)) is not null
                &&
                (name1 = Expect(TokenType.Name)) is not null
            )
            {
                return new TargetNode()
                {
                    Children = new NodeArray<GreenNode>([
                        name,
                        equal,
                        name1,
                    ]),
                };
            }
        }
        base.Reset(_mark);
        return null;
    }
    #endregion // Target
}

