namespace PySharp.Tokens;

public enum TokenType
{
    Name,
    Number,
    StringLiteral, // 'String' is ambiguous with 'string' in tests.
    FStringStart,
    FStringMiddle,
    FStringEnd,
    TStringStart,
    TStringMiddle,
    TStringEnd,
    Ellipsis,

    LeftParen,
    RightParen,
    LeftSquareBracket,
    RightSquareBracket,
    LeftBrace,
    RightBrace,
    Dot,
    Comma,
    Colon,
    ColonEqual,
    Semicolon,
    Equal,
    EqEqual,
    Plus,
    PlusEqual,
    Minus,
    MinusEqual,
    RightArrow,
    Star,
    StarEqual,
    DoubleStar,
    DoubleStarEqual,
    Slash,
    SlashEqual,
    DoubleSlash,
    DoubleSlashEqual,
    Percent,
    PercentEqual,
    Ampersand,
    AmpersandEqual,
    VertBar,
    VertBarEqual,
    At,
    AtEqual,
    Circumflex,
    CircumflexEqual,
    Tilde,
    Greater,
    GreaterEqual,
    RightShift,
    RightShiftEqual,
    Less,
    LessEqual,
    LeftShift,
    LeftShiftEqual,
    Exclamation,
    NotEqual,

    Dedent,
    Indent,
    NewLine,

    EndOfFile,
    Error,
    Comment,
    TriviaNewLine,
    WhiteSpace,
    BackSlash,
}
